send email whenever a profile update was made added
abozhiinov/devrix-starter-project pull request #1
Opened 2022-08-16 14:02 UTC by abozhiinov

2022-08-17 13:17 UTC, metodiew requested changes
https://github.com/abozhiinov/devrix-starter-project/pull/1/files
synced on-site,a few URLs and things to be updated
https://developer.wordpress.org/reference/functions/home_url/ - for links

no inline CSS

https://developer.wordpress.org/reference/functions/admin_url/ - for dashboard URLs

coding standards

`git config core.fileMode false` for filemode changes to be ingored

2022-08-17 14:26 UTC, abozhiinov commented
coding standarts, hardcoded urls fixed

2022-08-17 14:40 UTC, metodiew requested changes
Posted a few inline comments, let's update these and we should be done

2022-08-17 14:40 UTC, metodiew commented on wp-content/themes/twentytwenty-child/archive-student.php
> +        <h1 class="archive-title"><a href=<?php echo home_url( '/student' );?>>Students Archive</a></h1>
with the next iteration, we'll be using `get_post_type_archive_link`

2022-08-17 14:40 UTC, metodiew commented on wp-content/themes/twentytwenty-child/archive-student.php
> +    <div style="margin-top:50px">
some inline CSS that needs to be moved to a CSS class in the future iterations

2022-08-17 14:40 UTC, metodiew commented on wp-content/themes/twentytwenty-child/functions.php
> +        wp_enqueue_style( 'chld_thm_cfg_child', trailingslashit( get_stylesheet_directory_uri() ) . 'style.css', array(  ) );
for homework, you need to learn what different arguments in `wp_enqueue_style` are

2022-08-17 14:40 UTC, metodiew commented on wp-content/themes/twentytwenty-child/functions.php
> +    $items .= '<li><a href=' . admin_url('profile.php') . '>Profile Settings</a></li>';
coding standards

2022-08-17 14:40 UTC, metodiew commented on wp-content/themes/twentytwenty-child/functions.php
> +    <form method="post">
we might not need a `<form>` here + inline css

+ value fields are empty, I guess that's gonna be updated with the next PR?

2022-08-17 14:40 UTC, metodiew commented on wp-content/themes/twentytwenty-child/functions.php
> +    if ( get_post_type( $post_id ) !== 'event' ) return;
are we sure we are looking for `event` CPT?

2022-08-17 14:40 UTC, metodiew commented on wp-content/themes/twentytwenty-child/functions.php
> +    update_post_meta( $post_id, 'lives_in', $post->lives_in );
we need to make sure we are checking if the values are empty or not, otherwise we would update the post meta and add empty values on a number of cases

2022-08-19 09:43 UTC, metodiew commented on wp-content/themes/twentytwenty-child/functions.php
> +        wp_enqueue_style( 'chld_thm_cfg_child', trailingslashit( get_stylesheet_directory_uri() ) . 'style.css', array(  ) );
this can be improved, we'll sync

2022-08-19 09:45 UTC, metodiew commented on wp-content/themes/twentytwenty-child/single-student.php
> +            echo '<header class="student-name archive-header has-text-align-center">' . get_the_title() . '</header>';
formatting, we lack spacing here

2022-08-19 09:57 UTC, metodiew approved these changes
synced on site about te wp_enqueu* functions, some PHP Docblock updates and we can move forward with the next task

2022-08-19 10:00 UTC, merged